// ActivAnatomy — mapa anatômico detalhado usando o SVG fornecido pelo usuário.
(async function(){
  const COLORS_LOCAL={green:'#35aa67',yellow:'#e9a62f',red:'#db5651'};
  const neutral='#d7dfdd', base='#eef2f1';
  try{
    const parts=await Promise.all([1,2,3,4,5,6].map(i=>fetch(`anatomy/part${i}.txt`).then(r=>{if(!r.ok)throw new Error('anatomy '+i);return r.text()})));
    const bodybox=document.querySelector('.bodybox'); if(!bodybox)return;
    bodybox.innerHTML=`<svg id="detailed-anatomy" viewBox="138 425 700 905" preserveAspectRatio="xMidYMid meet" aria-label="Mapa anatômico detalhado"></svg><div class="view-labels"><div><b>Frente</b><span>vista anterior</span></div><div><b>Costas</b><span>vista posterior</span></div></div><div id="map-info" class="map-info">Passe o mouse ou toque em uma região colorida para ver o teste.</div><div id="map-tooltip" class="map-tooltip" role="tooltip"></div>`;
    const svg=document.getElementById('detailed-anatomy'); svg.innerHTML=parts.join('');
    svg.style.width='108%';svg.style.height='auto';svg.style.maxHeight='900px';svg.style.marginLeft='-4%';
    const paths=[...svg.querySelectorAll('path')];
    paths.forEach((p,i)=>{const n=i+1;p.id=`p${n}`;p.style.stroke='#fff';p.style.strokeWidth='1.05';p.style.transition='fill .18s ease,filter .18s ease';if(n===1){p.style.display='none';return;}if(n===2||n===52){p.dataset.base='1';p.style.fill=base;}else{p.dataset.muscle='1';p.style.fill=neutral;}});
    const ns='http://www.w3.org/2000/svg';[['D',205,1318],['E',320,1318],['E',690,1318],['D',815,1318]].forEach(([t,x,y])=>{const el=document.createElementNS(ns,'text');el.textContent=t;el.setAttribute('x',x);el.setAttribute('y',y);el.setAttribute('fill','#60706d');el.setAttribute('font-size','15');el.setAttribute('font-weight','800');svg.appendChild(el)});
    const style=document.createElement('style');style.textContent='.bodybox{overflow:visible!important;position:relative}.view-labels{display:grid;grid-template-columns:1fr 1fr;gap:14%;margin:-2px 9% 8px;text-align:center;color:#17302e}.view-labels div{display:flex;flex-direction:column;align-items:center;line-height:1.15}.view-labels b{font-size:14px}.view-labels span{font-size:10px;color:#7a8886;margin-top:3px}.map-info{margin:8px 8px 2px;padding:11px 12px;border:1px solid #dfe7e5;border-radius:12px;background:#f6f9f8;color:#687674;font-size:12px;line-height:1.35}.map-info.active{background:#edf6f4;color:#17302e;border-color:#c9ded9}.map-info b{display:block;font-size:13px;margin-bottom:3px}.map-info .mini{font-size:11px;color:#687674;margin-top:3px}.map-tooltip{position:fixed;z-index:9999;display:none;max-width:270px;padding:9px 11px;border-radius:10px;background:#17302e;color:#fff;box-shadow:0 8px 24px #0000002b;font-size:12px;line-height:1.3;pointer-events:none}.map-tooltip.show{display:block}.map-tooltip b{display:block;font-size:12px;margin-bottom:2px}.map-tooltip .tip-line{font-size:11px;opacity:.9}.map-tooltip .tip-pct{font-weight:900;margin-left:5px}#detailed-anatomy{display:block;margin-top:0!important;margin-bottom:-5px!important}.muscle-name{line-height:1.25}#detailed-anatomy [data-muscle].has-finding{cursor:pointer}#detailed-anatomy [data-muscle].has-finding:hover{filter:brightness(.92)}@media(max-width:700px){#detailed-anatomy{width:112%!important;margin-left:-6%!important;max-height:none!important}.view-labels{margin-left:7%;margin-right:7%;gap:10%}.map-info{margin-left:4px;margin-right:4px}.map-tooltip{display:none!important}}';document.head.appendChild(style);
    const G={
      shoulderFlex:{label:'Flexão de ombro • deltoide anterior / peitoral superior',left:['p4','p3'],right:['p23','p22']},shoulderAbd:{label:'Abdução de ombro • deltoide',left:['p4'],right:['p23']},shoulderAdd:{label:'Adução de ombro • peitoral / grande dorsal',left:['p3','p54'],right:['p22','p74']},shoulderER:{label:'Rotação externa • deltoide posterior / região infraespinal',left:['p55','p62'],right:['p75','p82']},shoulderIR:{label:'Rotação interna • peitoral / grande dorsal',left:['p3','p54'],right:['p22','p74']},shoulderExt:{label:'Extensão de ombro • deltoide posterior / grande dorsal',left:['p55','p54'],right:['p75','p74']},shoulder:{label:'Ombro / deltoide',left:['p4','p55'],right:['p23','p75']},biceps:{label:'Flexão de cotovelo • bíceps / braquial',left:['p5'],right:['p24']},triceps:{label:'Extensão de cotovelo • tríceps',left:['p56','p63','p64'],right:['p76','p83','p84']},hipAbd:{label:'Abdução de quadril • glúteo médio',left:['p68'],right:['p88']},hipAdd:{label:'Adução de quadril • adutores da coxa',left:['p19'],right:['p40']},hipFlex:{label:'Flexão de quadril • flexores / reto femoral proximal',left:['p17','p20'],right:['p38','p41']},hipExt:{label:'Extensão de quadril • glúteo máximo / isquiotibiais',left:['p67','p66'],right:['p87','p86']},quad:{label:'Extensão de joelho • quadríceps',left:['p13','p19','p20'],right:['p33','p40','p41']},ham:{label:'Flexão de joelho • isquiotibiais',left:['p61','p66'],right:['p81','p86']},tib:{label:'Dorsiflexão • tibial anterior / compartimento anterior',left:['p10','p12','p15'],right:['p30','p32','p36']},calf:{label:'Flexão plantar • gastrocnêmio / sóleo',left:['p69','p70','p71','p72'],right:['p89','p90','p91','p92']},forearm:{label:'Punho / antebraço',left:['p8','p18'],right:['p28','p39']}};
    window.targetFor=function(name){const s=String(name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(s.includes('ombro')){if(s.includes('rotacao externa'))return G.shoulderER;if(s.includes('rotacao interna'))return G.shoulderIR;if(s.includes('abdu'))return G.shoulderAbd;if(s.includes('adu'))return G.shoulderAdd;if(s.includes('flex'))return G.shoulderFlex;if(s.includes('ext'))return G.shoulderExt;return G.shoulder;}if(s.includes('cotovelo')&&s.includes('flex'))return G.biceps;if(s.includes('cotovelo')&&s.includes('ext'))return G.triceps;if(s.includes('quadril')&&s.includes('abdu'))return G.hipAbd;if(s.includes('quadril')&&s.includes('adu'))return G.hipAdd;if(s.includes('quadril')&&s.includes('flex'))return G.hipFlex;if(s.includes('quadril')&&s.includes('ext'))return G.hipExt;if(s.includes('joelho')&&s.includes('ext'))return G.quad;if(s.includes('joelho')&&s.includes('flex'))return G.ham;if(s.includes('tornozelo')&&(s.includes('dorsi')||s.includes('dorsal')))return G.tib;if(s.includes('tornozelo')&&(s.includes('plantar')||s.includes('plantiflex')))return G.calf;if(s.includes('punho'))return G.forearm;return null;};
    const info=document.getElementById('map-info'),tooltip=document.getElementById('map-tooltip');
    let findingsByPath={};
    window.resetBody=function(){svg.querySelectorAll('[data-muscle]').forEach(p=>{p.style.fill=neutral;p.classList.remove('has-finding')});findingsByPath={};if(info){info.className='map-info';info.textContent='Passe o mouse ou toque em uma região colorida para ver o teste.'}if(tooltip){tooltip.className='map-tooltip';tooltip.innerHTML=''}document.querySelectorAll('.finding-marker,.finding-number').forEach(x=>x.remove())};
    const isOxford=t=>t&&t.metric==='oxford';
    const testZone=t=>{if(isOxford(t)){const d=Math.abs(t.left-t.right);return d===0?'green':d<=1?'yellow':'red'}return zone(asym(t.left,t.right))};
    const sideZone=(t,side)=>{const z=testZone(t);if(t.left===t.right)return'green';const weak=t.left<t.right?'left':'right';return side===weak?z:'green'};
    const isFrontPath=id=>{const n=Number(String(id).replace('p',''));return n>=2&&n<=51};
    const findingText=f=>{const p=asym(f.test.left,f.test.right),side=f.side==='left'?'Esquerda':'Direita',val=f.side==='left'?f.test.left:f.test.right;return `<b>${f.test.name}</b>${f.mapLabel}<div class="mini">${side}: ${val.toFixed(1)} kg • assimetria ${p.toFixed(1)}%</div>`};
    const tooltipText=list=>list.map(f=>{const p=asym(f.test.left,f.test.right),side=f.side==='left'?'E':'D';return `<b>${f.test.name} <span class="tip-pct">${p.toFixed(1)}%</span></b><div class="tip-line">${f.mapLabel} • ${side}: ${(f.side==='left'?f.test.left:f.test.right).toFixed(1)} kg</div>`}).join('<div style="height:6px"></div>');
    const moveTooltip=e=>{if(!tooltip||!tooltip.classList.contains('show'))return;const gap=14,maxX=window.innerWidth-290,maxY=window.innerHeight-120;tooltip.style.left=Math.max(8,Math.min(maxX,e.clientX+gap))+'px';tooltip.style.top=Math.max(8,Math.min(maxY,e.clientY+gap))+'px'};
    paths.forEach(p=>{
      p.addEventListener('click',()=>{const list=findingsByPath[p.id];if(!list||!list.length||!info)return;info.className='map-info active';info.innerHTML=list.map(findingText).join('<div style="height:7px"></div>')});
      p.addEventListener('mouseenter',e=>{const list=findingsByPath[p.id];if(!list||!list.length||!tooltip)return;tooltip.innerHTML=tooltipText(list);tooltip.classList.add('show');moveTooltip(e)});
      p.addEventListener('mousemove',moveTooltip);
      p.addEventListener('mouseleave',()=>{if(tooltip)tooltip.classList.remove('show')});
    });
    window.paintTests=function(tests){resetBody();const chosen={},rank={green:1,yellow:2,red:3};const apply=(ids,z,finding)=>ids.forEach(id=>{if(!chosen[id]||rank[z]>rank[chosen[id]])chosen[id]=z;(findingsByPath[id]??=[]).push(finding)});tests.forEach(t=>{const g=targetFor(t.name);if(!g)return;const leftZone=sideZone(t,'left'),rightZone=sideZone(t,'right');const frontLeft=g.right.filter(isFrontPath),frontRight=g.left.filter(isFrontPath),backLeft=g.left.filter(id=>!isFrontPath(id)),backRight=g.right.filter(id=>!isFrontPath(id));apply(frontLeft,leftZone,{test:t,side:'left',mapLabel:g.label});apply(backLeft,leftZone,{test:t,side:'left',mapLabel:g.label});apply(frontRight,rightZone,{test:t,side:'right',mapLabel:g.label});apply(backRight,rightZone,{test:t,side:'right',mapLabel:g.label})});Object.entries(chosen).forEach(([id,z])=>{const el=document.getElementById(id);if(el){el.style.fill=COLORS_LOCAL[z];el.classList.add('has-finding')}});};
    window.render=function(tests){const box=document.getElementById('testes');box.innerHTML='';tests.forEach(t=>{const ox=isOxford(t),p=ox?Math.abs(t.left-t.right):asym(t.left,t.right),z=testZone(t),side=t.left<t.right?'Esquerda':t.right<t.left?'Direita':'Igual',g=targetFor(t.name),zl=sideZone(t,'left'),zr=sideZone(t,'right');const cn=z=>z==='green'?'verde':z==='yellow'?'amarelo':'vermelho';const fmt=v=>ox?`Oxford ${Number.isInteger(v)?v:v.toFixed(1)}/5`:`${v.toFixed(1)} kg`;const badge=ox?(p===0?'mesmo grau':`Δ ${p.toFixed(Number.isInteger(p)?0:1)} grau${p===1?'':'s'}`):`${p.toFixed(1)}%`;const d=document.createElement('div');d.className='test';d.innerHTML=`<div class="test-head"><b>${t.name}</b><span class="asym" style="color:${COLORS_LOCAL[z]}">${badge}</span></div>${g?`<div class="muscle-name">Mapa: ${g.label}</div>`:'<div class="muscle-name">Mapa: movimento ainda sem região definida</div>'}<div class="vals"><div class="val">Esquerda<b style="color:${COLORS_LOCAL[zl]}">${fmt(t.left)} • ${cn(zl)}</b></div><div class="val">Direita<b style="color:${COLORS_LOCAL[zr]}">${fmt(t.right)} • ${cn(zr)}</b></div><div class="val">Lado mais fraco<b>${side}</b></div></div>`;box.appendChild(d)});if(!tests.length)box.innerHTML='<div class="empty">Nenhum teste reconhecido.</div>';paintTests(tests);};
    const hint=document.querySelector('.map-title small');if(hint)hint.textContent='passe o mouse nas regiões coloridas';
  }catch(e){console.error('Falha ao carregar mapa anatômico detalhado',e)}
})();