// ActivAnatomy — autenticação individual em nuvem (Supabase)
(async function(){
  const SUPABASE_URL='https://vkizqqrccyvcabfxwyhz.supabase.co';
  const SUPABASE_KEY='sb_publishable_zQ-Go0vKh8aGdmZ53W7_2Q_meH4fpOo';
  const APP_URL='https://casalinhofisio.github.io/-physiomap/';

  if(!window.supabase){
    await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)}).catch(()=>{});
  }
  if(!window.supabase){console.error('Supabase não carregou');return}
  const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.activAnatomySupabase=sb;
  const main=document.querySelector('main.wrap');if(!main)return;main.style.display='none';

  const style=document.createElement('style');style.textContent=`
  .aa-auth{min-height:100vh;display:flex;align-items:center;justify-content:center;padding:22px;background:linear-gradient(145deg,#eef5f3,#f9fbfa);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;color:#17302e}
  .aa-auth-card{width:min(430px,100%);background:#fff;border:1px solid #dfe7e5;border-radius:26px;padding:28px;box-shadow:0 18px 55px #123b3920}.aa-auth-brand{font-size:34px;font-weight:800;letter-spacing:-1.2px;color:#145d58}.aa-auth-brand span{font-weight:300}.aa-auth-sub{font-size:13px;color:#687674;margin:3px 0 22px}
  .aa-tabs{display:grid;grid-template-columns:1fr 1fr;background:#eef3f2;border-radius:13px;padding:4px;margin-bottom:16px}.aa-tab{border:0;background:transparent;padding:10px;border-radius:10px;font-weight:800;color:#687674;cursor:pointer}.aa-tab.active{background:#fff;color:#145d58;box-shadow:0 2px 8px #00000010}
  .aa-google{width:100%;border:1px solid #d7d9dd;border-radius:12px;padding:12px 14px;background:#fff;color:#202124;font-weight:800;font-size:14px;cursor:pointer;display:flex;align-items:center;justify-content:center;gap:10px}.aa-google:hover{background:#f7f8f8}.aa-google:disabled{opacity:.6;cursor:wait}.aa-g{font-size:20px;font-weight:900;line-height:1;color:#4285f4}
  .aa-or{display:flex;align-items:center;gap:10px;margin:14px 0;color:#8a9290;font-size:11px}.aa-or:before,.aa-or:after{content:'';height:1px;background:#e1e5e4;flex:1}
  .aa-field{margin:11px 0}.aa-field label{display:block;font-size:11px;font-weight:800;color:#687674;margin:0 0 5px}.aa-field input{width:100%;border:1px solid #d6e1df;border-radius:12px;padding:13px 14px;font-size:15px;outline:none}.aa-field input:focus{border-color:#145d58;box-shadow:0 0 0 3px #145d5815}
  .aa-submit{width:100%;border:0;border-radius:12px;padding:13px 15px;background:#145d58;color:#fff;font-weight:900;font-size:15px;cursor:pointer;margin-top:8px}.aa-submit:disabled{opacity:.6;cursor:wait}.aa-forgot{display:block;width:100%;border:0;background:transparent;color:#a71727;font-size:12px;font-weight:800;cursor:pointer;padding:10px 4px 0;text-align:center}.aa-forgot:hover{text-decoration:underline}
  .aa-msg{display:none;margin-top:12px;padding:10px 11px;border-radius:10px;font-size:12px;line-height:1.35}.aa-msg.show{display:block}.aa-msg.ok{background:#edf8f1;color:#17683c}.aa-msg.err{background:#fff0ef;color:#9f312d}.aa-name,.aa-confirm{display:none}.aa-name.show,.aa-confirm.show{display:block}.aa-creator{margin-top:20px;padding-top:15px;border-top:1px solid #e5ecea;text-align:center;color:#7a8886;font-size:11px;line-height:1.45}.aa-creator b{color:#4f625f}
  .aa-account{display:flex;align-items:center;gap:8px;justify-content:flex-end}.aa-user{font-size:11px;color:#dcebea;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.aa-logout{border:1px solid #ffffff45;background:#ffffff12;color:#fff;border-radius:9px;padding:7px 9px;font-size:11px;font-weight:800;cursor:pointer}
  .aa-recovery{position:fixed;inset:0;z-index:30000;background:#080a0dcc;display:none;align-items:center;justify-content:center;padding:20px}.aa-recovery.show{display:flex}.aa-recovery-card{width:min(420px,100%);background:#10141a;color:#fff;border:1px solid #282e38;border-radius:22px;padding:24px;box-shadow:0 25px 80px #0008}.aa-recovery-card h3{margin:0 0 6px;font-size:22px}.aa-recovery-card p{margin:0 0 16px;color:#aeb4bd;font-size:12px;line-height:1.45}.aa-recovery-card input{width:100%;border:1px solid #303640;background:#151a21;color:#fff;border-radius:12px;padding:13px 14px;font-size:15px;outline:none;margin-bottom:10px}.aa-recovery-card button{width:100%;border:0;border-radius:12px;padding:13px;background:#b91f2f;color:#fff;font-weight:900;cursor:pointer}.aa-recovery-msg{font-size:12px;margin-top:10px;color:#ffb3b3}.aa-recovery-msg.ok{color:#9be3b4}
  @media(max-width:560px){.aa-auth-card{padding:22px;border-radius:20px}.aa-auth-brand{font-size:30px}.aa-account{justify-content:flex-start}.heroin{flex-wrap:wrap}}@media print{.aa-account{display:none!important}}
  `;document.head.appendChild(style);

  const auth=document.createElement('div');auth.className='aa-auth';auth.innerHTML=`<div class="aa-auth-card"><div class="aa-auth-brand">Activ<span>Anatomy</span></div><div class="aa-auth-sub">Dinamometria & Mapeamento de Força</div><div class="aa-tabs"><button class="aa-tab active" data-mode="login">Entrar</button><button class="aa-tab" data-mode="signup">Criar conta</button></div><button id="aaGoogle" class="aa-google" type="button"><span class="aa-g">G</span><span>Continuar com Google</span></button><div class="aa-or">ou continue com e-mail</div><div id="aaName" class="aa-field aa-name"><label>Nome</label><input id="aaNameInput" autocomplete="off" placeholder="Seu nome"></div><div class="aa-field"><label>E-mail</label><input id="aaEmail" type="email" autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="seu@email.com"></div><div class="aa-field"><label>Senha</label><input id="aaPassword" type="password" autocomplete="off" placeholder="Mínimo 6 caracteres"></div><div id="aaConfirmWrap" class="aa-field aa-confirm"><label>Repetir senha</label><input id="aaPasswordConfirm" type="password" autocomplete="new-password" placeholder="Digite a mesma senha novamente"></div><button id="aaSubmit" class="aa-submit">Entrar</button><button id="aaForgot" class="aa-forgot" type="button">Esqueci minha senha</button><div id="aaMsg" class="aa-msg"></div><div class="aa-creator">Criado por <b>Eduardo Casalinho Silva</b><br>Fisioterapeuta • CREFITO 437356-F</div></div>`;document.body.prepend(auth);

  const recovery=document.createElement('div');recovery.className='aa-recovery';recovery.innerHTML=`<div class="aa-recovery-card"><h3>Criar nova senha</h3><p>Digite uma nova senha para sua conta do ActivAnatomy.</p><input id="aaNewPassword" type="password" autocomplete="new-password" placeholder="Nova senha (mínimo 6 caracteres)"><input id="aaNewPassword2" type="password" autocomplete="new-password" placeholder="Repita a nova senha"><button id="aaUpdatePassword" type="button">Salvar nova senha</button><div id="aaRecoveryMsg" class="aa-recovery-msg"></div></div>`;document.body.appendChild(recovery);

  const tabs=[...auth.querySelectorAll('.aa-tab')],nameWrap=auth.querySelector('#aaName'),nameInput=auth.querySelector('#aaNameInput'),email=auth.querySelector('#aaEmail'),password=auth.querySelector('#aaPassword'),confirmWrap=auth.querySelector('#aaConfirmWrap'),passwordConfirm=auth.querySelector('#aaPasswordConfirm'),submit=auth.querySelector('#aaSubmit'),google=auth.querySelector('#aaGoogle'),forgot=auth.querySelector('#aaForgot'),msg=auth.querySelector('#aaMsg');let mode='login';
  const setMsg=(text,type='err')=>{msg.textContent=text;msg.className=`aa-msg show ${type}`},clearMsg=()=>{msg.textContent='';msg.className='aa-msg'};
  const clearCredentials=()=>{email.value='';password.value='';passwordConfirm.value='';nameInput.value=''};
  const setMode=m=>{mode=m;clearMsg();tabs.forEach(t=>t.classList.toggle('active',t.dataset.mode===m));nameWrap.classList.toggle('show',m==='signup');confirmWrap.classList.toggle('show',m==='signup');submit.textContent=m==='signup'?'Criar minha conta':'Entrar';forgot.style.display=m==='signup'?'none':'block';password.autocomplete=m==='signup'?'new-password':'off';if(m==='login')passwordConfirm.value=''};tabs.forEach(t=>t.addEventListener('click',()=>setMode(t.dataset.mode)));

  google.addEventListener('click',async()=>{clearMsg();google.disabled=true;try{const {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:APP_URL}});if(error)throw error}catch(err){const m=String(err?.message||err);setMsg(/provider|unsupported|enabled/i.test(m)?'O acesso com Google ainda precisa ser ativado no painel do projeto.':'Não foi possível entrar com Google: '+m)}finally{google.disabled=false}});

  forgot.addEventListener('click',async()=>{clearMsg();const e=email.value.trim();if(!e){setMsg('Digite seu e-mail acima para redefinir a senha.');email.focus();return}forgot.disabled=true;try{const {error}=await sb.auth.resetPasswordForEmail(e,{redirectTo:APP_URL});if(error)throw error;setMsg('Pronto. Enviamos um link para seu e-mail criar uma nova senha.','ok')}catch(err){setMsg('Não foi possível enviar o e-mail: '+String(err?.message||err))}finally{forgot.disabled=false}});

  const addAccountBar=user=>{document.querySelector('.aa-account')?.remove();const pro=document.querySelector('.pro');if(!pro)return;pro.innerHTML='';const display=user.email||user.user_metadata?.full_name||'Usuário';const bar=document.createElement('div');bar.className='aa-account';bar.innerHTML=`<span class="aa-user" title="${String(display).replace(/"/g,'&quot;')}">${display}</span><button class="aa-logout">Sair</button>`;pro.appendChild(bar);bar.querySelector('.aa-logout').addEventListener('click',async()=>{clearCredentials();await sb.auth.signOut();setTimeout(()=>{clearCredentials();setMode('login')},80)});const footer=document.querySelector('.footer');if(footer)footer.innerHTML='<b>ActivAnatomy</b> • Dinamometria & Mapeamento de Força'};
  const showApp=user=>{auth.style.display='none';main.style.display='';addAccountBar(user)},showAuth=(clear=true)=>{document.querySelector('.aa-account')?.remove();main.style.display='none';auth.style.display='flex';setMode('login');if(clear){clearCredentials();setTimeout(clearCredentials,80)}};

  submit.addEventListener('click',async()=>{clearMsg();const e=email.value.trim(),p=password.value,pc=passwordConfirm.value;if(!e||!p){setMsg('Preencha e-mail e senha.');return}if(p.length<6){setMsg('A senha precisa ter pelo menos 6 caracteres.');return}if(mode==='signup'&&p!==pc){setMsg('As duas senhas precisam ser iguais.');passwordConfirm.focus();return}submit.disabled=true;try{if(mode==='signup'){const {data,error}=await sb.auth.signUp({email:e,password:p,options:{data:{name:nameInput.value.trim()||e.split('@')[0]},emailRedirectTo:APP_URL}});if(error)throw error;if(data.session)await sb.auth.signOut();nameInput.value='';password.value='';passwordConfirm.value='';setTimeout(()=>{setMode('login');email.value=e;password.value='';setMsg('Conta criada. Agora entre com seu e-mail e senha. Se a confirmação por e-mail estiver ativada, confirme o e-mail antes de entrar.','ok');email.focus()},100)}else{const {data,error}=await sb.auth.signInWithPassword({email:e,password:p});if(error)throw error;showApp(data.user)}}catch(err){const m=String(err?.message||err);if(/Invalid login credentials/i.test(m))setMsg('E-mail ou senha incorretos.');else if(/already registered|already been registered/i.test(m))setMsg('Esse e-mail já está cadastrado. Tente entrar.');else setMsg('Não foi possível continuar: '+m)}finally{submit.disabled=false}});password.addEventListener('keydown',e=>{if(e.key==='Enter'&&mode==='login')submit.click()});passwordConfirm.addEventListener('keydown',e=>{if(e.key==='Enter'&&mode==='signup')submit.click()});

  const newPass=recovery.querySelector('#aaNewPassword'),newPass2=recovery.querySelector('#aaNewPassword2'),updatePass=recovery.querySelector('#aaUpdatePassword'),recoveryMsg=recovery.querySelector('#aaRecoveryMsg');
  updatePass.addEventListener('click',async()=>{recoveryMsg.textContent='';recoveryMsg.className='aa-recovery-msg';const a=newPass.value,b=newPass2.value;if(a.length<6){recoveryMsg.textContent='Use pelo menos 6 caracteres.';return}if(a!==b){recoveryMsg.textContent='As senhas não são iguais.';return}updatePass.disabled=true;try{const {error}=await sb.auth.updateUser({password:a});if(error)throw error;recoveryMsg.textContent='Senha alterada com sucesso.';recoveryMsg.className='aa-recovery-msg ok';setTimeout(()=>{recovery.classList.remove('show');location.replace(APP_URL)},900)}catch(err){recoveryMsg.textContent='Não foi possível alterar: '+String(err?.message||err)}finally{updatePass.disabled=false}});

  sb.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){auth.style.display='none';main.style.display='none';recovery.classList.add('show');return}session?.user?showApp(session.user):showAuth(true)});
  const {data:{session}}=await sb.auth.getSession();session?.user?showApp(session.user):showAuth(true);
})();