// ActivAnatomy — camada comercial v2: apresentação, status de acesso, assinatura e cupom vitalício.
(function(){
  const CHECKOUT='https://checkout.infinitepay.io/duducasalinho/5VJKdL6gbe';
  const ready=(fn)=>{let n=0;const t=setInterval(()=>{const auth=document.querySelector('.aa-auth');if(auth&&window.activAnatomySupabase){clearInterval(t);fn(auth)}else if(++n>80)clearInterval(t)},100)};
  ready((auth)=>{
    const sb=window.activAnatomySupabase;if(document.getElementById('aa-commercial-style'))return;
    const style=document.createElement('style');style.id='aa-commercial-style';style.textContent=`
      .aa-auth{padding:28px!important;background:radial-gradient(circle at 18% 12%,rgba(112,17,32,.28),transparent 34%),linear-gradient(135deg,#0c0f14 0%,#101117 55%,#0b0d12 100%)!important}
      .aa-commercial-shell{width:min(1180px,100%);display:grid;grid-template-columns:minmax(0,1.35fr) minmax(340px,410px);gap:58px;align-items:center}
      .aa-commercial-hero{padding:10px 0;color:#fff;max-width:720px}
      .aa-commercial-kicker{display:inline-flex;align-items:center;padding:8px 13px;border:1px solid #ffffff24;border-radius:999px;background:#ffffff10;color:#f7f8f8;font-size:11px;font-weight:900;letter-spacing:.45px;text-transform:uppercase;box-shadow:inset 0 1px 0 #ffffff12}
      .aa-commercial-hero h1{font-size:clamp(42px,4.7vw,68px);line-height:.98;letter-spacing:-3.2px;margin:20px 0 18px;max-width:700px;color:#f7f8fa!important}
      .aa-commercial-hero h1 span{color:#e92f45!important}
      .aa-commercial-lead{font-size:17px;line-height:1.55;color:#c8cdd3!important;max-width:650px;margin:0 0 24px}
      .aa-commercial-bullets{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;max-width:690px}
      .aa-commercial-bullet{display:flex;gap:10px;align-items:flex-start;font-size:13px;line-height:1.45;font-weight:700;color:#edf0f2!important;background:#ffffff08;border:1px solid #ffffff12;border-radius:14px;padding:13px 14px;min-height:66px;box-sizing:border-box}
      .aa-commercial-bullet b{color:#fff!important}
      .aa-commercial-check{width:23px;height:23px;border-radius:50%;display:grid;place-items:center;flex:0 0 auto;background:#e7f7f0;color:#0e7157;font-size:13px;font-weight:1000;box-shadow:0 0 0 1px #ffffff14}
      .aa-commercial-price{margin-top:22px;display:flex;align-items:stretch;gap:12px;flex-wrap:wrap}
      .aa-commercial-pricebox{background:linear-gradient(180deg,#ffffff,#f1f3f4)!important;color:#11151a!important;border-radius:16px;padding:14px 18px;min-width:176px;box-shadow:0 12px 30px #0004}
      .aa-commercial-pricebox small{display:block;color:#5d646b!important;font-size:10px;font-weight:900;letter-spacing:.45px;margin-bottom:3px}
      .aa-commercial-pricebox strong{font-size:28px;color:#b71f32!important;letter-spacing:-.7px}
      .aa-commercial-note{font-size:12.5px;line-height:1.45;color:#c2c8cd!important;max-width:250px;background:#ffffff06;border:1px solid #ffffff10;border-radius:16px;padding:13px 15px;display:flex;align-items:center}
      .aa-auth-card:before{display:none!important;content:none!important}.aa-commercial-mini{display:none!important}
      .aa-access-pill{display:inline-flex;border-radius:999px;padding:6px 10px;font-size:11px;font-weight:900;margin-right:5px}.aa-access-pill.life{background:#e4f5ec;color:#14613e}.aa-access-pill.trial{background:#fff4d9;color:#7d5a00}.aa-access-pill.paid{background:#e9eefc;color:#2e4d8d}.aa-access-pill.expired{background:#ffe9e8;color:#9a302c}.aa-subscribe-btn,.aa-coupon-btn{border:0;border-radius:9px;padding:8px 11px;font-size:11px;font-weight:900;cursor:pointer;margin-right:5px}.aa-subscribe-btn{background:#c51d34;color:#fff}.aa-coupon-btn{border:1px solid #ffffff45;background:#ffffff12;color:#fff}
      .aa-coupon-modal{position:fixed;inset:0;z-index:40000;background:#09100ecc;display:none;align-items:center;justify-content:center;padding:18px}.aa-coupon-modal.show{display:flex}.aa-coupon-card{width:min(420px,100%);background:#fff;border-radius:22px;padding:24px}.aa-coupon-card input{width:100%;padding:13px;border:1px solid #ddd;border-radius:12px}.aa-coupon-actions{display:flex;gap:8px;margin-top:10px}.aa-coupon-actions button{flex:1;padding:12px;border:0;border-radius:11px;font-weight:900}.aa-coupon-use{background:#145d58;color:#fff}.aa-coupon-msg{font-size:12px;margin-top:10px}.aa-coupon-msg.ok{color:#14613e}.aa-coupon-msg.err{color:#9a302c}
      @media(max-width:960px){.aa-commercial-shell{grid-template-columns:1fr;gap:26px}.aa-commercial-hero{text-align:center;max-width:760px;margin:auto}.aa-commercial-hero h1{margin-left:auto;margin-right:auto}.aa-commercial-lead{margin-left:auto;margin-right:auto}.aa-commercial-bullets{max-width:650px;margin:auto;text-align:left}.aa-commercial-price{justify-content:center}.aa-commercial-note{text-align:left}.aa-auth-card{margin:auto}}
      @media(max-width:560px){.aa-auth{padding:14px!important}.aa-commercial-hero h1{font-size:34px;letter-spacing:-1.8px}.aa-commercial-lead{font-size:14px}.aa-commercial-bullets{grid-template-columns:1fr}.aa-commercial-bullet{min-height:auto}.aa-commercial-price{margin-top:16px}.aa-commercial-pricebox,.aa-commercial-note{width:100%;max-width:none;box-sizing:border-box}}
    `;document.head.appendChild(style);
    const card=auth.querySelector('.aa-auth-card');if(!card)return;
    const shell=document.createElement('div');shell.className='aa-commercial-shell';const hero=document.createElement('section');hero.className='aa-commercial-hero';hero.innerHTML=`<div class="aa-commercial-kicker">⚡ AVALIAÇÃO DE FORÇA MAIS VISUAL</div><h1>Transforme números em uma avaliação que o paciente <span>entende.</span></h1><p class="aa-commercial-lead">O ActivAnatomy transforma avaliações de força em um mapa anatômico visual, facilita a identificação de assimetrias e acompanha a evolução do paciente.</p><div class="aa-commercial-bullets"><div class="aa-commercial-bullet"><span class="aa-commercial-check">✓</span><span><b>Tem ActivForce?</b> Importe o PDF da avaliação e visualize os resultados no mapa anatômico.</span></div><div class="aa-commercial-bullet"><span class="aa-commercial-check">✓</span><span><b>Não tem dinamômetro?</b> Use a Escala de Oxford e gere o mapa anatômico para apresentar ao paciente.</span></div><div class="aa-commercial-bullet"><span class="aa-commercial-check">✓</span><span>Histórico individual e evolução de cada paciente.</span></div><div class="aa-commercial-bullet"><span class="aa-commercial-check">✓</span><span>Comparação entre avaliações e relatórios em PDF.</span></div></div><div class="aa-commercial-price"><div class="aa-commercial-pricebox"><small>DEPOIS DO TESTE GRÁTIS</small><strong>R$ 19,99</strong> /mês</div><div class="aa-commercial-note">Crie sua conta e teste por 30 dias. Nenhuma cobrança é feita ao criar a conta.</div></div>`;card.parentNode.insertBefore(shell,card);shell.append(hero,card);
    const modal=document.createElement('div');modal.className='aa-coupon-modal';modal.innerHTML=`<div class="aa-coupon-card"><h3>Resgatar cupom</h3><p>O cupom vitalício fica vinculado à sua conta.</p><input id="aaCouponCode" placeholder="Digite seu cupom"><div class="aa-coupon-actions"><button class="aa-coupon-close">Cancelar</button><button class="aa-coupon-use">Liberar acesso</button></div><div class="aa-coupon-msg"></div></div>`;document.body.appendChild(modal);const cInput=modal.querySelector('#aaCouponCode'),cMsg=modal.querySelector('.aa-coupon-msg'),cUse=modal.querySelector('.aa-coupon-use');modal.querySelector('.aa-coupon-close').onclick=()=>modal.classList.remove('show');
    async function loadAccess(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data}=await sb.from('account_access').select('access_level,status,trial_started_at,trial_ends_at').eq('user_id',user.id).maybeSingle();const bar=document.querySelector('.aa-account');if(!bar)return;bar.querySelectorAll('.aa-access-pill,.aa-coupon-btn,.aa-subscribe-btn').forEach(x=>x.remove());let label='30 dias grátis',cls='trial';if(data?.access_level==='lifetime'){label='Acesso vitalício';cls='life'}else if(data?.access_level==='paid'){label='Assinatura ativa';cls='paid'}else if(data?.access_level==='trial'){const days=data.trial_ends_at?Math.max(0,Math.ceil((new Date(data.trial_ends_at)-Date.now())/86400000)):30;label=`${days} ${days===1?'dia restante':'dias restantes'}`;cls=days>0?'trial':'expired'}else{label='Teste encerrado';cls='expired'}const pill=document.createElement('span');pill.className=`aa-access-pill ${cls}`;pill.textContent=label;bar.insertBefore(pill,bar.firstChild);if(data?.access_level!=='lifetime'){const sub=document.createElement('button');sub.className='aa-subscribe-btn';sub.type='button';sub.textContent='Assinar · R$ 19,99';sub.onclick=()=>window.location.href=CHECKOUT;bar.insertBefore(sub,bar.querySelector('.aa-logout'));const cup=document.createElement('button');cup.className='aa-coupon-btn';cup.type='button';cup.textContent='Tenho um cupom';cup.onclick=()=>{cInput.value='';cMsg.textContent='';modal.classList.add('show')};bar.insertBefore(cup,bar.querySelector('.aa-logout'))}}
    cUse.onclick=async()=>{const code=cInput.value.trim();if(!code)return;cUse.disabled=true;try{const {data,error}=await sb.rpc('redeem_lifetime_coupon',{p_code:code});if(error)throw error;cMsg.textContent=data?.message||'Cupom processado.';cMsg.className='aa-coupon-msg '+(data?.ok?'ok':'err');if(data?.ok)setTimeout(()=>{modal.classList.remove('show');loadAccess()},700)}catch(e){cMsg.textContent='Cupom inválido ou já utilizado.';cMsg.className='aa-coupon-msg err'}finally{cUse.disabled=false}};sb.auth.onAuthStateChange((_e,s)=>{if(s?.user)setTimeout(loadAccess,250)});setTimeout(loadAccess,350);
  });
})();