// ActivAnatomy — cabeçalho premium estável
(function(){
  function icon(name){const p={assessment:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/>',patients:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/>',oxford:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><path d="M14 2v6h6"/><path d="M8 13h8M8 17h8"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${p[name]||''}</svg>`}
  function enhance(){
    const hero=document.querySelector('.hero'),hi=hero?.querySelector('.heroin'),nav=hero?.querySelector('.aa-nav'),pro=hero?.querySelector('.pro');
    if(!hero||!hi||!nav||!pro)return false;
    const brand=hi.firstElementChild;if(!brand)return false;
    brand.classList.add('aa-premium-brand');
    const h1=brand.querySelector('h1');if(h1)h1.innerHTML='ActivAnatomy<span class="aa-brand-dot">.</span>';
    const p=brand.querySelector('p');if(p){p.textContent='MOVIMENTO GERA NOVAS POSSIBILIDADES';p.classList.add('aa-premium-tagline')}
    nav.querySelectorAll('.aa-nav-btn').forEach(b=>{if(b.dataset.premiumDone)return;const pg=b.dataset.page,l=b.textContent.trim();b.innerHTML=icon(pg==='assessment'?'assessment':pg==='patients'?'patients':'oxford')+`<span>${l}</span>`;b.dataset.premiumDone='1'});
    pro.classList.add('aa-premium-account');
    let trigger=pro.querySelector('.aa-account-trigger');if(!trigger){trigger=document.createElement('button');trigger.type='button';trigger.className='aa-account-trigger';trigger.setAttribute('aria-label','Abrir conta');trigger.innerHTML='<span class="aa-avatar"></span><span class="aa-chevron">⌄</span>';pro.prepend(trigger)}
    const user=pro.querySelector('.aa-user'),logout=pro.querySelector('.aa-logout');if(user)user.classList.add('aa-user-hidden');if(logout){logout.textContent='Sair da conta';logout.classList.add('aa-premium-logout')}
    trigger.onclick=e=>{e.stopPropagation();pro.classList.toggle('open')};
    return true;
  }
  const s=document.createElement('style');s.textContent=`
  .hero{position:relative;overflow:visible!important;background:#090d12!important;border:1px solid #1c222b!important;border-radius:18px!important;padding:0 24px!important;min-height:92px;box-shadow:0 14px 38px #10151d26!important;color:#fff!important}
  .heroin{position:relative;z-index:1;min-height:92px;display:grid!important;grid-template-columns:260px minmax(470px,1fr) minmax(220px,auto)!important;align-items:center!important;gap:22px!important;width:100%!important}
  .aa-premium-brand{display:flex;align-items:center;min-width:0!important;overflow:visible!important}.aa-premium-brand h1{font-size:34px!important;font-weight:780!important;letter-spacing:-1.25px!important;white-space:nowrap;margin:0!important}.aa-brand-dot{color:#ff3947!important}.aa-premium-tagline{display:none!important}
  .aa-nav{margin:0!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:10px!important;flex-wrap:nowrap!important;overflow:visible!important;min-width:470px!important;width:max-content!important;position:relative!important;z-index:50!important}
  .aa-nav-btn{display:flex!important;align-items:center!important;justify-content:center!important;gap:8px!important;min-width:140px!important;min-height:48px!important;padding:12px 18px!important;border:1px solid #3a414b!important;background:#151a20!important;color:#f2f4f7!important;border-radius:12px!important;font-size:12px!important;font-weight:760!important;white-space:nowrap!important;cursor:pointer!important;pointer-events:auto!important;position:relative!important;z-index:51!important;overflow:visible!important}
  .aa-nav-btn svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round;pointer-events:none!important}.aa-nav-btn span{pointer-events:none!important}.aa-nav-btn:hover{background:#20262e!important;border-color:#69717c!important}.aa-nav-btn.active{background:#4a171e!important;border-color:#ff4658!important;color:#fff!important;box-shadow:0 7px 20px #9d13252c!important}
  .pro.aa-premium-account{position:relative!important;z-index:10!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;opacity:1!important;min-width:220px!important;padding-left:15px!important;border-left:1px solid #ffffff24!important;text-align:left!important;overflow:visible!important}.aa-account-trigger{display:none!important}.aa-user-hidden{display:block!important;color:#fff!important;font-size:11px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important;max-width:230px!important}.aa-premium-logout{display:block!important;margin-left:10px!important;background:#1b2026!important;color:#fff!important;border:1px solid #4b5159!important;border-radius:10px!important;padding:8px 12px!important;cursor:pointer!important}
  @media(max-width:1100px){.heroin{grid-template-columns:230px minmax(420px,1fr) auto!important;gap:12px!important}.aa-premium-brand h1{font-size:29px!important}.aa-nav-btn{min-width:125px!important;padding:11px 13px!important}.aa-nav{min-width:410px!important}}
  @media(max-width:980px){.hero{padding:14px 18px!important}.heroin{grid-template-columns:1fr auto!important;gap:10px 12px!important;min-height:auto!important}.aa-premium-brand{grid-column:1;grid-row:1}.pro.aa-premium-account{grid-column:2;grid-row:1;min-width:0!important;border-left:0!important;padding-left:0!important}.aa-user-hidden{display:none!important}.aa-premium-logout{padding:7px 10px!important}.aa-nav{grid-column:1/-1;grid-row:2;justify-content:flex-start!important;overflow-x:auto!important;min-width:0!important;width:100%!important;padding:2px 0 1px!important}.aa-nav-btn{min-width:125px!important}}
  @media(max-width:560px){.wrap{padding:10px!important}.hero{padding:13px 14px 11px!important;border-radius:15px!important;margin-bottom:14px!important}.aa-premium-brand h1{font-size:26px!important}.aa-nav{gap:6px!important}.aa-nav-btn{min-width:118px!important;min-height:42px!important;padding:9px 10px!important;font-size:11px!important}.aa-nav-btn svg{width:16px;height:16px}.pro.aa-premium-account{min-width:auto!important}}
  @media print{.hero{display:none!important}}`;
  document.head.appendChild(s);
  let n=0,t=setInterval(()=>{enhance();if(++n>200)clearInterval(t)},100);
})();