// ActivAnatomy — gestor de pacientes + histórico visual por usuário
(async function(){
 const wait=async()=>{for(let i=0;i<100;i++){if(window.activAnatomySupabase)return window.activAnatomySupabase;await new Promise(r=>setTimeout(r,100))}return null};
 const sb=await wait(); if(!sb)return;
 const main=document.querySelector('main.wrap'),hero=document.querySelector('.hero'),grid=document.querySelector('.grid');if(!main||!hero||!grid)return;
 const style=document.createElement('style');style.textContent=`
 .aa-nav{display:flex;gap:8px;align-items:center;margin-top:14px;flex-wrap:wrap}.aa-nav-btn{border:1px solid #ffffff35;background:#ffffff12;color:#fff;border-radius:11px;padding:9px 12px;font-size:12px;font-weight:800;cursor:pointer}.aa-nav-btn.active{background:#fff;color:#145d58}.aa-add-patient{margin-top:10px;width:100%;border:1px solid #b8cfcb;background:#eef6f4;color:#145d58;border-radius:12px;padding:11px 13px;font-weight:900;cursor:pointer}.aa-patients{display:none;background:#fff;border:1px solid #dfe7e5;border-radius:20px;padding:18px;box-shadow:0 5px 18px #183d3914}.aa-patients.show{display:block}.aa-head{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.aa-head h2,.aa-head h3{margin:0}.aa-primary{border:0;background:#145d58;color:#fff;border-radius:12px;padding:11px 14px;font-weight:900;cursor:pointer}.aa-search,.aa-select{width:100%;margin:14px 0 10px;border:1px solid #d6e1df;border-radius:12px;padding:12px 13px;font-size:14px;background:#fff}.aa-list{display:grid;gap:9px}.aa-row{border:1px solid #dfe7e5;border-radius:14px;padding:12px 13px;display:flex;justify-content:space-between;gap:12px;align-items:center;background:#fbfcfc}.aa-name{font-weight:900!important;font-size:15px!important;line-height:1.2!important;color:#17302e!important;display:block!important;visibility:visible!important}.aa-meta{font-size:11px;color:#687674;margin-top:4px}.aa-actions{display:flex;gap:6px;flex-wrap:wrap}.aa-small{border:0;border-radius:9px;padding:8px 10px;font-size:11px;font-weight:800;cursor:pointer;background:#e8efee;color:#17302e}.aa-small.open{background:#145d58;color:#fff}.aa-small.danger{background:#fff0ef;color:#9f312d}.aa-empty{text-align:center;padding:28px;color:#687674}.aa-detail{display:none}.aa-detail.show{display:block}.aa-back{border:0;background:transparent;color:#145d58;font-weight:900;cursor:pointer;padding:0;margin-bottom:12px}.aa-history{margin-top:18px}.aa-savebox{margin-top:12px;border-top:1px solid #e4ecea;padding-top:12px}.aa-savebox label{font-size:11px;font-weight:800;color:#687674}.aa-save-status{font-size:11px;margin-top:7px;color:#687674}.aa-modal-bg{position:fixed;inset:0;background:#0d26247a;display:none;align-items:center;justify-content:center;padding:18px;z-index:9999}.aa-modal-bg.show{display:flex}.aa-modal{width:min(460px,100%);background:#fff;border-radius:20px;padding:20px;box-shadow:0 20px 70px #0004}.aa-modal h3{margin:0 0 14px}.aa-modal label{display:block;font-size:11px;font-weight:800;color:#687674;margin:10px 0 5px}.aa-modal input,.aa-modal textarea{width:100%;border:1px solid #d6e1df;border-radius:11px;padding:11px 12px;font:inherit}.aa-modal textarea{min-height:80px;resize:vertical}.aa-modal-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.aa-cancel{border:0;background:#e8efee;color:#17302e;border-radius:11px;padding:10px 13px;font-weight:800;cursor:pointer}
 .aa-eval-card{border:1px solid #dfe7e5;border-radius:16px;padding:13px;background:#fbfcfc}.aa-eval-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.aa-mini-map{margin-top:10px;border:1px solid #e3ebe9;border-radius:13px;background:#fff;padding:6px;overflow:hidden}.aa-mini-map svg{display:block;width:100%;height:180px}.aa-summary{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.aa-pill{font-size:10px;font-weight:800;background:#eef4f3;color:#49605d;border-radius:999px;padding:5px 8px}.aa-eval-view{display:none;margin-top:14px}.aa-eval-view.show{display:block}.aa-eval-grid{display:grid;grid-template-columns:minmax(300px,1fr) minmax(320px,1fr);gap:16px}.aa-eval-map{border:1px solid #dfe7e5;border-radius:16px;background:#fbfcfc;padding:8px;overflow:hidden}.aa-eval-map svg{width:100%;height:auto;max-height:700px;display:block}.aa-test-card{border:1px solid #dfe7e5;border-radius:13px;padding:11px;margin-bottom:8px}.aa-test-values{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:7px}.aa-test-values div{background:#f5f8f7;border-radius:9px;padding:8px;font-size:10px;color:#687674}.aa-test-values b{display:block;font-size:13px;color:#17302e;margin-top:2px}.aa-rom-title{margin:16px 0 8px}.aa-compare-panel{display:none;margin-top:14px;border:1px solid #dfe7e5;border-radius:16px;padding:12px;background:#f8fbfa}.aa-compare-panel.show{display:block}.aa-compare-controls{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;align-items:end}.aa-compare-controls select{margin:0}.aa-compare-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.aa-compare-col{border:1px solid #dfe7e5;border-radius:14px;padding:10px;background:#fff}.aa-compare-col svg{width:100%;height:310px;display:block}.aa-compare-table{margin-top:12px;overflow:auto}.aa-compare-table table{width:100%;border-collapse:collapse;font-size:11px}.aa-compare-table th,.aa-compare-table td{padding:8px;border-bottom:1px solid #e4ecea;text-align:left;white-space:nowrap}.aa-good{color:#18894d}.aa-warn{color:#b77712}.aa-bad{color:#b53c38}
 @media(max-width:800px){.aa-eval-grid,.aa-compare-grid{grid-template-columns:1fr}.aa-compare-controls{grid-template-columns:1fr}.aa-test-values{grid-template-columns:1fr 1fr}.aa-test-values div:last-child{grid-column:1/-1}}@media(max-width:560px){.aa-row{align-items:flex-start;flex-direction:column}.aa-actions{width:100%}.aa-small{flex:1}}@media print{.aa-nav,.aa-add-patient,.aa-patients,.aa-savebox{display:none!important}}`;
 document.head.appendChild(style);
 const heroText=hero.querySelector('.heroin > div:first-child');if(heroText&&!hero.querySelector('.aa-nav')){const nav=document.createElement('div');nav.className='aa-nav';nav.innerHTML='<button class="aa-nav-btn active" data-page="assessment">Avaliação</button><button class="aa-nav-btn" data-page="patients">Pacientes</button>';heroText.appendChild(nav)}
 const importCard=grid.querySelector('.card');if(importCard&&!document.querySelector('.aa-add-patient')){const add=document.createElement('button');add.className='aa-add-patient';add.textContent='+ Adicionar paciente';const drop=importCard.querySelector('.drop');if(drop)drop.insertAdjacentElement('afterend',add);else importCard.prepend(add);add.onclick=()=>openModal()}
 const saveBox=document.createElement('div');saveBox.className='aa-savebox';saveBox.innerHTML='<label>Salvar esta avaliação no paciente</label><select class="aa-select" id="aaEvalPatient"><option value="">Selecione um paciente...</option></select><button class="aa-primary" id="aaSaveEval" type="button">Salvar avaliação</button><div class="aa-save-status" id="aaSaveStatus">Importe um PDF ActivForce e selecione o paciente.</div>';if(importCard)importCard.appendChild(saveBox);
 const page=document.createElement('section');page.className='aa-patients';page.innerHTML=`<div id="aaPatientIndex"><div class="aa-head"><div><h2>Meus pacientes</h2><div class="hint">Histórico salvo somente na sua conta.</div></div><button class="aa-primary" id="aaNewPatient">+ Adicionar paciente</button></div><input class="aa-search" id="aaSearch" placeholder="Buscar paciente pelo nome..."><div class="aa-list" id="aaList"><div class="aa-empty">Carregando...</div></div></div><div class="aa-detail" id="aaDetail"><button class="aa-back" id="aaBack">← Voltar aos pacientes</button><div class="aa-head"><div><h2 id="aaDetailName"></h2><div class="hint" id="aaDetailMeta"></div></div><button class="aa-primary" id="aaNewAssessment">+ Nova avaliação</button></div><div class="aa-history"><div class="aa-head"><h3>Histórico de avaliações</h3><button class="aa-small" id="aaCompare" disabled>Comparar avaliações</button></div><div class="aa-compare-panel" id="aaComparePanel"><div class="aa-compare-controls"><div><label class="hint">Avaliação 1</label><select class="aa-select" id="aaCompareA"></select></div><div><label class="hint">Avaliação 2</label><select class="aa-select" id="aaCompareB"></select></div><button class="aa-primary" id="aaRunCompare">Comparar</button></div><div id="aaCompareResult"></div></div><div class="aa-list" id="aaHistory"></div><div class="aa-eval-view" id="aaEvalView"></div></div></div>`;grid.insertAdjacentElement('afterend',page);
 const modal=document.createElement('div');modal.className='aa-modal-bg';modal.innerHTML='<div class="aa-modal"><h3 id="aaModalTitle">Adicionar paciente</h3><label>Nome do paciente *</label><input id="aaPName"><label>Data de nascimento</label><input id="aaPBirth" type="date"><label>Telefone</label><input id="aaPPhone"><label>Observações</label><textarea id="aaPNotes"></textarea><div class="aa-modal-actions"><button class="aa-cancel" id="aaCancel">Cancelar</button><button class="aa-primary" id="aaSavePatient">Salvar paciente</button></div></div>';document.body.appendChild(modal);
 let patients=[],user=null,editing=null,selected=null,historyRows=[];
 const list=page.querySelector('#aaList'),search=page.querySelector('#aaSearch'),sel=saveBox.querySelector('#aaEvalPatient'),status=saveBox.querySelector('#aaSaveStatus');
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),fmt=d=>{if(!d)return'';const x=String(d).slice(0,10).split('-');return x.length===3?`${x[2]}/${x[1]}/${x[0]}`:d};
 const asym=(a,b)=>{const top=Math.max(Math.abs(Number(a)),Math.abs(Number(b)));return top?Math.abs(Number(a)-Number(b))/top*100:0};
 function safeName(p){const n=String(p?.name||'').trim();return n||'Paciente sem nome'}
 function render(){const q=search.value.trim().toLowerCase(),shown=patients.filter(p=>safeName(p).toLowerCase().includes(q));list.innerHTML=shown.length?shown.map(p=>`<div class="aa-row" data-id="${p.id}"><div><div class="aa-name">${esc(safeName(p))}</div><div class="aa-meta">${p.birth_date?'Nascimento: '+fmt(p.birth_date):'Paciente cadastrado'}</div></div><div class="aa-actions"><button class="aa-small open" data-a="open">Abrir</button><button class="aa-small" data-a="edit">Editar</button><button class="aa-small danger" data-a="delete">Excluir</button></div></div>`).join(''):'<div class="aa-empty">Nenhum paciente cadastrado ainda.</div>';sel.innerHTML='<option value="">Selecione um paciente...</option>'+patients.map(p=>`<option value="${p.id}">${esc(safeName(p))}</option>`).join('');if(selected)sel.value=selected.id}
 async function load(){if(!user)return;const {data,error}=await sb.from('patients').select('*').eq('user_id',user.id).order('name');if(error){list.innerHTML='<div class="aa-empty">Erro ao carregar pacientes.</div>';return}patients=data||[];render()}
 function openModal(p=null){editing=p?.id||null;modal.querySelector('#aaModalTitle').textContent=p?'Editar paciente':'Adicionar paciente';modal.querySelector('#aaPName').value=p?.name||'';modal.querySelector('#aaPBirth').value=p?.birth_date||'';modal.querySelector('#aaPPhone').value=p?.phone||'';modal.querySelector('#aaPNotes').value=p?.notes||'';modal.classList.add('show')}
 async function savePatient(){const name=modal.querySelector('#aaPName').value.trim();if(!name)return alert('Digite o nome do paciente.');const payload={name,birth_date:modal.querySelector('#aaPBirth').value||null,phone:modal.querySelector('#aaPPhone').value.trim()||null,notes:modal.querySelector('#aaPNotes').value.trim()||null,updated_at:new Date().toISOString()};let error;if(editing)({error}=await sb.from('patients').update(payload).eq('id',editing).eq('user_id',user.id));else{payload.user_id=user.id;({error}=await sb.from('patients').insert(payload))}if(error)return alert('Não foi possível salvar: '+error.message);modal.classList.remove('show');editing=null;await load()}
 function clonePaintedMap(tests,height='auto'){
   const source=document.getElementById('detailed-anatomy');if(!source)return '<div class="aa-empty">Mapa anatômico carregando...</div>';
   const clone=source.cloneNode(true);clone.removeAttribute('id');clone.style.width='100%';clone.style.height=height;clone.style.margin='0';clone.style.maxHeight='none';clone.querySelectorAll('[data-muscle]').forEach(p=>{p.style.fill='#d7dfdd';p.classList.remove('has-finding')});
   const rank={green:1,yellow:2,red:3},colors={green:'#35aa67',yellow:'#e9a62f',red:'#db5651'},chosen={};
   const front=id=>{const n=Number(String(id).replace('p',''));return n>=2&&n<=51};
   (tests||[]).forEach(t=>{const g=typeof window.targetFor==='function'?window.targetFor(t.name):null;if(!g)return;const p=asym(t.left,t.right),z=p<=10?'green':p<=20?'yellow':'red',weak=Number(t.left)<Number(t.right)?'left':Number(t.right)<Number(t.left)?'right':null;const sideZ=s=>!weak?'green':s===weak?z:'green';const sets={left:[...g.right.filter(front),...g.left.filter(id=>!front(id))],right:[...g.left.filter(front),...g.right.filter(id=>!front(id))]};['left','right'].forEach(side=>sets[side].forEach(id=>{const zz=sideZ(side);if(!chosen[id]||rank[zz]>rank[chosen[id]])chosen[id]=zz}))});
   Object.entries(chosen).forEach(([id,z])=>{const el=clone.querySelector(`[id="${id}"]`);if(el)el.style.fill=colors[z]});
   clone.querySelectorAll('text').forEach(t=>{t.style.pointerEvents='none'});return clone.outerHTML;
 }
 function summaryPills(e){const tests=Array.isArray(e.tests)?e.tests:[],rom=Array.isArray(e.rom_tests)?e.rom_tests:[],worst=tests.length?Math.max(...tests.map(t=>asym(t.left,t.right))):0;const cls=worst>20?'aa-bad':worst>10?'aa-warn':'aa-good';return `<div class="aa-summary"><span class="aa-pill">${tests.length} força</span>${rom.length?`<span class="aa-pill">${rom.length} ROM</span>`:''}${tests.length?`<span class="aa-pill ${cls}">maior assimetria ${worst.toFixed(1)}%</span>`:''}</div>`}
 function renderHistoryCard(e){return `<div class="aa-eval-card" data-evalid="${e.id}"><div class="aa-eval-top"><div><div class="aa-name">Avaliação • ${fmt(e.evaluation_date||e.created_at)}</div><div class="aa-meta">${esc(e.source||'ActivForce')} • salvo em ${fmt(e.created_at)}</div>${summaryPills(e)}</div><div class="aa-actions"><button class="aa-small open" data-open-eval="${e.id}">Ver avaliação</button><button class="aa-small danger" data-del-eval="${e.id}">Excluir</button></div></div><div class="aa-mini-map">${clonePaintedMap(e.tests||[],'180px')}</div></div>`}
 async function openPatient(id){selected=patients.find(p=>p.id===id);if(!selected)return;page.querySelector('#aaPatientIndex').style.display='none';page.querySelector('#aaDetail').classList.add('show');page.querySelector('#aaDetailName').textContent=safeName(selected);page.querySelector('#aaDetailMeta').textContent=selected.birth_date?'Nascimento: '+fmt(selected.birth_date):'Histórico do paciente';sel.value=id;await loadHistory()}
 async function loadHistory(){const h=page.querySelector('#aaHistory');h.innerHTML='<div class="aa-empty">Carregando avaliações...</div>';page.querySelector('#aaEvalView').classList.remove('show');page.querySelector('#aaEvalView').innerHTML='';const {data,error}=await sb.from('evaluations').select('*').eq('patient_id',selected.id).eq('user_id',user.id).order('created_at',{ascending:false});if(error){h.innerHTML='<div class="aa-empty">Não foi possível carregar o histórico.</div>';return}historyRows=data||[];h.innerHTML=historyRows.length?historyRows.map(renderHistoryCard).join(''):'<div class="aa-empty">Nenhuma avaliação salva para este paciente.</div>';const cmp=page.querySelector('#aaCompare');cmp.disabled=historyRows.length<2;const opts=historyRows.map(e=>`<option value="${e.id}">${fmt(e.evaluation_date||e.created_at)}</option>`).join('');page.querySelector('#aaCompareA').innerHTML=opts;page.querySelector('#aaCompareB').innerHTML=opts;if(historyRows[1])page.querySelector('#aaCompareB').value=historyRows[1].id}
 function testCard(t,metric='kg'){const p=asym(t.left,t.right),weak=Number(t.left)<Number(t.right)?'Esquerda':Number(t.right)<Number(t.left)?'Direita':'Igual',cls=p>20?'aa-bad':p>10?'aa-warn':'aa-good';return `<div class="aa-test-card"><div class="aa-eval-top"><b>${esc(t.name)}</b><b class="${cls}">${p.toFixed(1)}%</b></div><div class="aa-test-values"><div>Esquerda<b>${Number(t.left).toFixed(1)} ${metric}</b></div><div>Direita<b>${Number(t.right).toFixed(1)} ${metric}</b></div><div>Menor lado<b>${weak}</b></div></div></div>`}
 function openEvaluation(id){const e=historyRows.find(x=>x.id===id);if(!e)return;const view=page.querySelector('#aaEvalView'),tests=Array.isArray(e.tests)?e.tests:[],rom=Array.isArray(e.rom_tests)?e.rom_tests:[];view.innerHTML=`<button class="aa-back" id="aaCloseEval">← Voltar ao histórico</button><div class="aa-head"><div><h3>Avaliação de ${fmt(e.evaluation_date||e.created_at)}</h3><div class="hint">${esc(e.file_name||'Relatório ActivForce')}</div></div></div><div class="aa-eval-grid"><div class="aa-eval-map">${clonePaintedMap(tests,'auto')}</div><div><h3>Força muscular</h3>${tests.length?tests.map(t=>testCard(t,t.metric||'kg')).join(''):'<div class="aa-empty">Sem testes de força salvos.</div>'}${rom.length?`<h3 class="aa-rom-title">Mobilidade / ADM</h3>${rom.map(t=>testCard(t,'°')).join('')}`:''}</div></div>`;view.classList.add('show');page.querySelector('#aaHistory').style.display='none';page.querySelector('#aaComparePanel').classList.remove('show');view.querySelector('#aaCloseEval').onclick=()=>{view.classList.remove('show');page.querySelector('#aaHistory').style.display='grid'};view.scrollIntoView({behavior:'smooth',block:'start'})}
 function compareRows(a,b){const map=new Map();[...(a.tests||[])].forEach(t=>map.set(String(t.name).toLowerCase(),{name:t.name,a:t}));[...(b.tests||[])].forEach(t=>{const k=String(t.name).toLowerCase();if(!map.has(k))map.set(k,{name:t.name});map.get(k).b=t});return [...map.values()].map(r=>{const pa=r.a?asym(r.a.left,r.a.right):null,pb=r.b?asym(r.b.left,r.b.right):null,delta=pa!=null&&pb!=null?pb-pa:null;return `<tr><td>${esc(r.name)}</td><td>${pa==null?'—':pa.toFixed(1)+'%'}</td><td>${pb==null?'—':pb.toFixed(1)+'%'}</td><td class="${delta==null?'':delta<0?'aa-good':delta>0?'aa-bad':''}">${delta==null?'—':(delta>0?'+':'')+delta.toFixed(1)+' p.p.'}</td></tr>`}).join('')}
 function runCompare(){const a=historyRows.find(x=>x.id===page.querySelector('#aaCompareA').value),b=historyRows.find(x=>x.id===page.querySelector('#aaCompareB').value);if(!a||!b||a.id===b.id)return alert('Escolha duas avaliações diferentes.');page.querySelector('#aaCompareResult').innerHTML=`<div class="aa-compare-grid"><div class="aa-compare-col"><div class="aa-name">${fmt(a.evaluation_date||a.created_at)}</div>${clonePaintedMap(a.tests||[],'310px')}</div><div class="aa-compare-col"><div class="aa-name">${fmt(b.evaluation_date||b.created_at)}</div>${clonePaintedMap(b.tests||[],'310px')}</div></div><div class="aa-compare-table"><table><thead><tr><th>Teste</th><th>${fmt(a.evaluation_date||a.created_at)}</th><th>${fmt(b.evaluation_date||b.created_at)}</th><th>Evolução da assimetria</th></tr></thead><tbody>${compareRows(a,b)}</tbody></table></div>`}
 async function saveEvaluation(){if(!user)return;const patientId=sel.value;if(!patientId)return alert('Selecione um paciente.');const tests=(window.currentTests||window.tests||[]).filter(t=>t&&t.left!=null&&t.right!=null);const rom=(window.currentROMTests||[]).filter(t=>t&&t.left!=null&&t.right!=null);if(!tests.length&&!rom.length)return alert('Primeiro importe um PDF ActivForce reconhecido.');const meta=window.currentPatient||window.patientData||{};const dateRaw=meta.date||meta.evaluation_date||new Date().toISOString().slice(0,10);const iso=/^\d{4}-\d{2}-\d{2}$/.test(dateRaw)?dateRaw:new Date().toISOString().slice(0,10);const payload={user_id:user.id,patient_id:patientId,evaluation_date:iso,source:'ActivForce',file_name:window.currentFileName||null,tests:tests.map(t=>({name:t.name,left:Number(t.left),right:Number(t.right),metric:t.metric||'kg'})),rom_tests:rom.map(t=>({name:t.name,left:Number(t.left),right:Number(t.right),metric:'°'})),patient_data:meta};status.textContent='Salvando...';const {error}=await sb.from('evaluations').insert(payload);if(error){status.textContent='Não foi possível salvar.';return alert(error.message)}status.textContent='Avaliação salva com mapa, achados e histórico.';if(selected?.id===patientId)loadHistory()}
 function setPage(x){document.querySelectorAll('.aa-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===x));if(x==='patients'){grid.style.display='none';page.classList.add('show');load()}else{grid.style.display='';page.classList.remove('show')}}
 hero.onclick=e=>{const b=e.target.closest('.aa-nav-btn');if(b)setPage(b.dataset.page)};page.querySelector('#aaNewPatient').onclick=()=>openModal();search.oninput=render;modal.querySelector('#aaCancel').onclick=()=>modal.classList.remove('show');modal.querySelector('#aaSavePatient').onclick=savePatient;saveBox.querySelector('#aaSaveEval').onclick=saveEvaluation;page.querySelector('#aaBack').onclick=()=>{selected=null;historyRows=[];page.querySelector('#aaPatientIndex').style.display='';page.querySelector('#aaDetail').classList.remove('show');page.querySelector('#aaEvalView').classList.remove('show');page.querySelector('#aaHistory').style.display='grid'};page.querySelector('#aaNewAssessment').onclick=()=>{sel.value=selected.id;setPage('assessment');window.scrollTo({top:0,behavior:'smooth'})};page.querySelector('#aaCompare').onclick=()=>page.querySelector('#aaComparePanel').classList.toggle('show');page.querySelector('#aaRunCompare').onclick=runCompare;
 list.onclick=async e=>{const r=e.target.closest('.aa-row');if(!r)return;const p=patients.find(x=>x.id===r.dataset.id),a=e.target.closest('[data-a]')?.dataset.a;if(a==='open')openPatient(p.id);if(a==='edit')openModal(p);if(a==='delete'&&confirm(`Excluir ${safeName(p)} e todo o histórico?`)){const {error}=await sb.from('patients').delete().eq('id',p.id).eq('user_id',user.id);if(error)alert(error.message);else load()}};
 page.querySelector('#aaHistory').onclick=async e=>{const open=e.target.closest('[data-open-eval]')?.dataset.openEval;if(open)return openEvaluation(open);const id=e.target.closest('[data-del-eval]')?.dataset.delEval;if(id&&confirm('Excluir esta avaliação?')){await sb.from('evaluations').delete().eq('id',id).eq('user_id',user.id);loadHistory()}};
 sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(user)load();else{patients=[];render();setPage('assessment')}});const {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user)load();
})();