// ActivAnatomy — entrada universal de força: dinamometria e Oxford/MRC
(function(){
 const METHODS={dynamometry:{label:'Dinamometria',unit:'kg'},oxford:{label:'Oxford / MRC',unit:'0–5'}};
 const MOVEMENTS={
  'Ombro':['Flexão','Extensão','Abdução','Adução','Rotação externa','Rotação interna'],
  'Cotovelo':['Flexão','Extensão'],
  'Punho':['Flexão','Extensão','Desvio radial','Desvio ulnar'],
  'Quadril':['Flexão','Extensão','Abdução','Adução','Rotação externa','Rotação interna'],
  'Joelho':['Flexão','Extensão'],
  'Tornozelo':['Dorsiflexão','Flexão plantar','Inversão','Eversão']
 };
 const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 function boot(){const card=document.querySelector('.grid .card');if(!card||document.getElementById('aaUniversalForce'))return;
  const style=document.createElement('style');style.textContent=`.aauf{margin-top:14px;border:1px solid #d8e5e2;border-radius:16px;padding:14px;background:#f8fbfa}.aauf h3{margin:0 0 5px;color:#17302e}.aauf-sub{font-size:11px;color:#687674;margin-bottom:12px}.aauf-tabs{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.aauf-tab{border:1px solid #cbdad7;background:#fff;color:#31524e;border-radius:10px;padding:8px 10px;font-weight:800;cursor:pointer}.aauf-tab.active{background:#145d58;color:#fff}.aauf-grid{display:grid;grid-template-columns:1.1fr 1.1fr .8fr .8fr;gap:8px}.aauf label{display:block;font-size:10px;font-weight:800;color:#687674;margin-bottom:4px}.aauf select,.aauf input{width:100%;box-sizing:border-box;border:1px solid #d6e1df;border-radius:10px;padding:10px;background:#fff}.aauf-actions{display:flex;gap:8px;margin-top:10px;flex-wrap:wrap}.aauf-add{border:0;background:#145d58;color:#fff;border-radius:10px;padding:10px 13px;font-weight:900;cursor:pointer}.aauf-clear{border:0;background:#e8efee;color:#17302e;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.aauf-list{display:grid;gap:7px;margin-top:12px}.aauf-row{display:grid;grid-template-columns:1fr auto auto auto;gap:8px;align-items:center;background:#fff;border:1px solid #e0e9e7;border-radius:11px;padding:9px}.aauf-badge{font-size:10px;font-weight:900;background:#eef4f3;border-radius:999px;padding:5px 7px}.aauf-del{border:0;background:#fff0ef;color:#9f312d;border-radius:8px;padding:6px 8px;cursor:pointer}.aauf-note{font-size:10px;color:#687674;margin-top:10px}@media(max-width:700px){.aauf-grid{grid-template-columns:1fr 1fr}.aauf-row{grid-template-columns:1fr auto}.aauf-row .aauf-badge{display:none}}`;
  document.head.appendChild(style);
  const box=document.createElement('section');box.id='aaUniversalForce';box.className='aauf';box.innerHTML=`<h3>Nova avaliação de força</h3><div class="aauf-sub">Use um relatório compatível ou insira os valores manualmente. O método de medição fica registrado na avaliação.</div><div class="aauf-tabs"><button class="aauf-tab active" data-m="dynamometry">Dinamometria</button><button class="aauf-tab" data-m="oxford">Oxford / MRC</button></div><div class="aauf-grid"><div><label>Região</label><select id="aaufRegion"></select></div><div><label>Movimento</label><select id="aaufMovement"></select></div><div><label>Esquerdo</label><input id="aaufLeft" inputmode="decimal"></div><div><label>Direito</label><input id="aaufRight" inputmode="decimal"></div></div><div class="aauf-actions"><button class="aauf-add" id="aaufAdd">+ Adicionar teste</button><button class="aauf-clear" id="aaufClear">Limpar testes manuais</button></div><div class="aauf-list" id="aaufList"></div><div class="aauf-note" id="aaufNote">Dinamometria: informe valores numéricos. Oxford/MRC: valores inteiros de 0 a 5. O sistema não trata Oxford como kg nem calcula percentual de força entre graus da escala.</div>`;
  const save=document.querySelector('.aa-savebox');if(save)save.insertAdjacentElement('beforebegin',box);else card.appendChild(box);
  let method='dynamometry',manual=[];const region=box.querySelector('#aaufRegion'),movement=box.querySelector('#aaufMovement'),left=box.querySelector('#aaufLeft'),right=box.querySelector('#aaufRight'),list=box.querySelector('#aaufList');
  region.innerHTML=Object.keys(MOVEMENTS).map(x=>`<option>${x}</option>`).join('');function moves(){movement.innerHTML=MOVEMENTS[region.value].map(x=>`<option>${x}</option>`).join('')}moves();region.onchange=moves;
  function num(v){return Number(String(v).replace(',','.'))}function valid(v){return Number.isFinite(v)}
  function sync(){window.currentManualForceTests=manual.slice();const dyn=manual.filter(x=>x.method==='dynamometry').map(x=>({name:x.name,left:x.left,right:x.right,metric:'kg',method:'dynamometry',source:'Manual'}));window.currentTests=dyn;window.currentOxfordTests=manual.filter(x=>x.method==='oxford').map(x=>({...x,metric:'Oxford/MRC'}));list.innerHTML=manual.map((x,i)=>`<div class="aauf-row"><b>${x.name}</b><span class="aauf-badge">${METHODS[x.method].label}</span><span>E ${x.left} · D ${x.right} ${x.method==='dynamometry'?'kg':''}</span><button class="aauf-del" data-i="${i}">Excluir</button></div>`).join('');document.dispatchEvent(new CustomEvent('activanatomy:manual-force-change',{detail:{tests:manual}}));}
  box.querySelectorAll('.aauf-tab').forEach(b=>b.onclick=()=>{method=b.dataset.m;box.querySelectorAll('.aauf-tab').forEach(x=>x.classList.toggle('active',x===b));left.value='';right.value=''});
  box.querySelector('#aaufAdd').onclick=()=>{const l=num(left.value),r=num(right.value);if(!valid(l)||!valid(r))return alert('Informe os valores dos dois lados.');if(method==='oxford'&&(!Number.isInteger(l)||!Number.isInteger(r)||l<0||l>5||r<0||r>5))return alert('Na escala Oxford/MRC, use valores inteiros de 0 a 5.');manual.push({name:`${region.value} ${movement.value}`,region:region.value,movement:movement.value,left:l,right:r,method,unit:METHODS[method].unit,source:'Manual'});left.value='';right.value='';sync()};
  box.querySelector('#aaufClear').onclick=()=>{manual=[];sync()};list.onclick=e=>{const b=e.target.closest('[data-i]');if(!b)return;manual.splice(Number(b.dataset.i),1);sync()};sync();
 }
 let n=0;const t=setInterval(()=>{boot();if(++n>50||document.getElementById('aaUniversalForce'))clearInterval(t)},100);
})();